version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.9.0
